-- =============================================================================
-- IVY — TELEGRAM EXPENSE AGENT + TEAM MEMBER AUTH · schema
-- =============================================================================
-- Run each numbered block SEPARATELY in the Supabase SQL editor.
--
-- Depends on add-ivy-schema.sql having been run first (ivy_capitals,
-- ivy_expenses, and the expense_category / expense_source enums).
--
-- SECURITY MODEL
--   * brand_id and role for any Telegram sender are resolved SERVER-SIDE from
--     their chat_id via owner_channels. They are never read from a message.
--   * owner_link_tokens are single-use, short-lived, claimed atomically.
--   * phone on brand_members is a DISPLAY LABEL ONLY — it authorizes nothing.
-- =============================================================================


-- ── 1a. Team members ─────────────────────────────────────────────────────────
create table if not exists brand_members (
  id         uuid primary key default gen_random_uuid(),
  brand_id   uuid not null references brands(id) on delete cascade,
  name       text not null,
  role       text not null default 'media_buyer' check (role in ('owner','media_buyer')),
  phone      text,                              -- DISPLAY LABEL ONLY, never auth
  created_at timestamptz not null default now()
);
create index if not exists idx_brand_members_brand on brand_members (brand_id);


-- ── 1b. Telegram channel binding + deep-link tokens ──────────────────────────
-- NOTE: the "Luna owner-agent" work referenced in the build spec was not present
-- in this repo, so these tables are created here in full (member_id + role are
-- built in rather than added by a later ALTER).

-- One row per verified (channel, channel_user_id). This is the ONLY place a
-- Telegram sender is mapped to a brand + role.
create table if not exists owner_channels (
  id               uuid primary key default gen_random_uuid(),
  brand_id         uuid not null references brands(id) on delete cascade,
  member_id        uuid references brand_members(id) on delete set null,
  role             text not null default 'owner' check (role in ('owner','media_buyer')),
  channel          text not null default 'telegram',
  channel_user_id  text not null,               -- Telegram chat_id (string)
  telegram_user_id text,                         -- Telegram from.id (string)
  verified_at      timestamptz,
  created_at       timestamptz not null default now(),
  unique (channel, channel_user_id)
);
create index if not exists idx_owner_channels_brand on owner_channels (brand_id);

-- Single-use, short-lived deep-link tokens. Generated by an owner for a member.
create table if not exists owner_link_tokens (
  token      text primary key,
  brand_id   uuid not null references brands(id) on delete cascade,
  member_id  uuid references brand_members(id) on delete cascade,
  role       text not null default 'owner' check (role in ('owner','media_buyer')),
  expires_at timestamptz not null,
  used_at    timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_owner_link_tokens_brand on owner_link_tokens (brand_id);


-- ── 1c. Atomic expense + deduction function ──────────────────────────────────
-- The ONLY path that writes an expense. Locks the capital row, verifies it
-- belongs to the brand, inserts the expense, decrements the STORED balance —
-- all in one transaction so concurrent writes can't lose an update.
--
-- Overspend policy: this ALLOWS the balance to go negative (records overspend
-- rather than blocking it). To hard-block, add an insufficient_funds guard
-- before the insert.
create or replace function ivy_log_expense(
  p_brand_id   uuid,
  p_amount     numeric,
  p_category   expense_category,
  p_capital_id uuid,
  p_note       text,
  p_source     expense_source default 'text',
  p_spent_at   timestamptz default now()
) returns json
language plpgsql
as $$
declare
  v_balance     numeric;
  v_expense_id  uuid;
  v_new_balance numeric;
begin
  if p_amount is null or p_amount <= 0 then
    return json_build_object('ok', false, 'error', 'invalid_amount');
  end if;

  -- lock the capital row and confirm it belongs to this brand
  select current_balance into v_balance
  from ivy_capitals
  where id = p_capital_id and brand_id = p_brand_id
  for update;

  if not found then
    return json_build_object('ok', false, 'error', 'capital_not_found');
  end if;

  -- insert expense
  insert into ivy_expenses (brand_id, amount, category, capital_id, source, note, spent_at)
  values (p_brand_id, p_amount, p_category, p_capital_id, p_source, coalesce(p_note, ''), p_spent_at)
  returning id into v_expense_id;

  -- deduct from the stored balance (allowed to go negative)
  v_new_balance := v_balance - p_amount;
  update ivy_capitals set current_balance = v_new_balance where id = p_capital_id;

  return json_build_object(
    'ok', true,
    'expense_id', v_expense_id,
    'new_balance', v_new_balance,
    'went_negative', (v_new_balance < 0)
  );
end $$;


-- ── 4a. Per-chat pending expense (multi-turn slot filling) ───────────────────
-- Survives Railway restarts so a half-filled expense isn't lost between turns.
create table if not exists ivy_pending_expenses (
  chat_id    text primary key,
  brand_id   uuid not null,
  slots      jsonb not null default '{}'::jsonb,  -- {amount, category, capital_id, note, spent_at}
  updated_at timestamptz not null default now()
);
